<a href="https://colab.research.google.com/github/ansharahzulfiqar4-crypto/Numpy_tasks/blob/main/numpy_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Name:Sayeda Ansharah
#Roll no:892366

In [ ]:
#Task 1
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)

print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Array: [10 20 30 40 50]
Sum: 150
Average: 30.0
Maximum: 50
Minimum: 10


In [ ]:
#Task 2
import numpy as np

marks = np.array([45, 80, 30, 90, 55, 20])

passed = marks[marks >= 50]

print("Values greater than or equal to 50:")
print(passed)


Values greater than or equal to 50:
[80 90 55]


In [ ]:
#Task 3
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
#Task 4
import numpy as np

# Generate 10 random marks between 40 and 100
marks = np.random.randint(40, 105, 10)

print("Random Student Marks:")
print(marks)

print("\nAverage Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))



Random Student Marks:
[60 52 51 47 78 58 94 88 65 81]

Average Marks: 67.4
Highest Marks: 94
Lowest Marks: 47


In [ ]:
#Task 5
import numpy as np

marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

# Passing marks are 50
passed = marks[marks >= 50]
failed = marks[marks < 50]

print("Marks:")
print(marks)

print("\nPassed Marks:")
print(passed)

print("Failed Marks:")
print(failed)

print("\nNumber of Passed Students:", len(passed))
print("Number of Failed Students:", len(failed))


Marks:
[35 67 89 45 90 22 70 58]

Passed Marks:
[67 89 90 70 58]
Failed Marks:
[35 45 22]

Number of Passed Students: 5
Number of Failed Students: 3


In [ ]:
 # numpy practice

import numpy as np

# Create a NumPy array
numbers = np.array([10, 20, 30, 40])

# Print the array
print("Array:", numbers)

# Calculate the mean (average)
print("Mean:", np.mean(numbers))

# Find the maximum value
print("Maximum:", np.max(numbers))


Array: [10 20 30 40]
Mean: 25.0
Maximum: 40


In [ ]:
# Python List vs NumPy Array

import numpy as np

# Normal Python List
marks_list = [70, 80, 90, 60]

print("Python List:")
print(marks_list)

# NumPy Array
marks = np.array([70, 80, 90, 60])

print("NumPy Array:")
print(marks)

# NumPy calculation
marks2 = np.array([70, 80, 90])

print("Original Marks:")
print(marks2)

print("After adding 5:")
print(marks2 + 5)


Python List:
[70, 80, 90, 60]
NumPy Array:
[70 80 90 60]
Original Marks:
[70 80 90]
After adding 5:
[75 85 95]


In [ ]:
# 3. Creating NumPy Arrays

import numpy as np

# One-Dimensional Array
numbers = np.array([10, 20, 30, 40])

print("1D Array:")
print(numbers)


# Two-Dimensional Array
marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 95]
])

print("\n2D Array:")
print(marks)


1D Array:
[10 20 30 40]

2D Array:
[[70 80 90]
 [60 75 85]
 [88 92 95]]


In [ ]:
# 4. Important Array Properties

import numpy as np

# Create a 2D NumPy array
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Print the array
print("Array:")
print(data)

# ndim - Number of dimensions
print("\nNumber of dimensions:")
print(data.ndim)

# shape - Number of rows and columns
print("\nShape:")
print(data.shape)

# size - Total number of values
print("\nTotal size:")
print(data.size)

# dtype - Data type of values
print("\nData type:")
print(data.dtype)


Array:
[[10 20 30]
 [40 50 60]]

Number of dimensions:
2

Shape:
(2, 3)

Total size:
6

Data type:
int64


In [ ]:
# 5. Indexing

import numpy as np

# Create a NumPy array
numbers = np.array([10, 20, 30, 40, 50])

# Positive Indexing
print("First value:", numbers[0])
print("Third value:", numbers[2])

# Negative Indexing
print("Last value:", numbers[-1])
print("Second last value:", numbers[-2])


First value: 10
Third value: 30
Last value: 50
Second last value: 40


In [ ]:
# 6. Indexing in a 2D Array

import numpy as np

# Create a 2D array
marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])

# Print the complete array
print("Marks:")
print(marks)

# Access values using row and column
print("First row, second column:")
print(marks[0, 1])

print("Second row, third column:")
print(marks[1, 2])

print("First row, first column:")
print(marks[0, 0])


Marks:
[[70 80 90]
 [60 75 85]]
First row, second column:
80
Second row, third column:
85
First row, first column:
70


In [ ]:
# 7. Slicing

import numpy as np

# Create a NumPy array
numbers = np.array([10, 20, 30, 40, 50])

# Print complete array
print("Original Array:")
print(numbers)

# Slicing
print("\nSlicing [1:4]:")
print(numbers[1:4])

# More examples
print("\nSlicing [0:3]:")
print(numbers[0:3])

print("\nSlicing [2:5]:")
print(numbers[2:5])

print("\nSlicing [:3]:")
print(numbers[:3])

print("\nSlicing [2:]:")
print(numbers[2:])


Original Array:
[10 20 30 40 50]

Slicing [1:4]:
[20 30 40]

Slicing [0:3]:
[10 20 30]

Slicing [2:5]:
[30 40 50]

Slicing [:3]:
[10 20 30]

Slicing [2:]:
[30 40 50]


In [ ]:
# 8. Vectorized Operations

import numpy as np

# Create a NumPy array
numbers = np.array([10, 20, 30, 40])

# Addition
print("Original Array:")
print(numbers)

print("\nAdd 5:")
print(numbers + 5)

# Multiplication
print("\nMultiply by 2:")
print(numbers * 2)

# Subtraction
print("\nSubtract 5:")
print(numbers - 5)

# Division
print("\nDivide by 2:")
print(numbers / 2)


Original Array:
[10 20 30 40]

Add 5:
[15 25 35 45]

Multiply by 2:
[20 40 60 80]

Subtract 5:
[ 5 15 25 35]

Divide by 2:
[ 5. 10. 15. 20.]


In [ ]:
# 9. Operations Between Two Arrays

import numpy as np

# Create two NumPy arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# Print both arrays
print("Array a:")
print(a)

print("\nArray b:")
print(b)

# Addition
print("\nAddition:")
print(a + b)

# Subtraction
print("\nSubtraction:")
print(a - b)

# Multiplication
print("\nMultiplication:")
print(a * b)

# Division
print("\nDivision:")
print(a / b)


Array a:
[10 20 30]

Array b:
[1 2 3]

Addition:
[11 22 33]

Subtraction:
[ 9 18 27]

Multiplication:
[10 40 90]

Division:
[10. 10. 10.]


In [ ]:
# 10. Mathematical Functions

import numpy as np

# Square Root
numbers = np.array([4, 9, 16, 25])

print("Square Root:")
print(np.sqrt(numbers))


# Power
numbers = np.array([2, 3, 4])

print("\nPower:")
print(np.power(numbers, 2))


# Absolute Value
numbers = np.array([-10, -5, 4, 8])

print("\nAbsolute Value:")
print(np.abs(numbers))


# Round
numbers = np.array([4.2, 5.7, 8.9])

print("\nRound:")
print(np.round(numbers))


Square Root:
[2. 3. 4. 5.]

Power:
[ 4  9 16]

Absolute Value:
[10  5  4  8]

Round:
[4. 6. 9.]


In [ ]:
# 11. Aggregation Functions

import numpy as np

# Create a NumPy array
marks = np.array([70, 85, 60, 95, 80])

# Sum
print("Sum:")
print(np.sum(marks))

# Average / Mean
print("\nAverage:")
print(np.mean(marks))

# Maximum
print("\nMaximum:")
print(np.max(marks))

# Minimum
print("\nMinimum:")
print(np.min(marks))

# Median
print("\nMedian:")
print(np.median(marks))

# Standard Deviation
print("\nStandard Deviation:")
print(np.std(marks))


Sum:
390

Average:
78.0

Maximum:
95

Minimum:
60

Median:
80.0

Standard Deviation:
12.083045973594572


In [ ]:
# 12. Conditions in NumPy

import numpy as np

# Create a NumPy array
marks = np.array([30, 50, 80, 45, 90, 20])

# Check which marks are greater than or equal to 50
print("Marks:")
print(marks)

print("\nMarks >= 50:")
print(marks >= 50)

# Other conditions
print("\nMarks > 50:")
print(marks > 50)

print("\nMarks < 50:")
print(marks < 50)

print("\nMarks == 50:")
print(marks == 50)


Marks:
[30 50 80 45 90 20]

Marks >= 50:
[False  True  True False  True False]

Marks > 50:
[False False  True False  True False]

Marks < 50:
[ True False False  True False  True]

Marks == 50:
[False  True False False False False]


In [ ]:
# 13. Filtering Data

import numpy as np

# Create a NumPy array
marks = np.array([30, 50, 80, 45, 90, 20])

# Get passed marks
passed = marks[marks >= 50]

print("All Marks:")
print(marks)

print("\nPassed Marks:")
print(passed)

# Get failed marks
failed = marks[marks < 50]

print("\nFailed Marks:")
print(failed)


All Marks:
[30 50 80 45 90 20]

Passed Marks:
[50 80 90]

Failed Marks:
[30 45 20]


In [ ]:
# 14. Reshape

import numpy as np

# Create a 1D array
numbers = np.array([1, 2, 3, 4, 5, 6])

# Print original array
print("Original Array:")
print(numbers)

# Reshape into 2 rows and 3 columns
new_array = numbers.reshape(2, 3)

print("\nReshaped Array:")
print(new_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# 15. Flatten

import numpy as np

# Create a 2D array
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Print original array
print("Original 2D Array:")
print(data)

# Convert 2D array into 1D array
flat_data = data.flatten()

print("\nFlattened 1D Array:")
print(flat_data)


Original 2D Array:
[[1 2 3]
 [4 5 6]]

Flattened 1D Array:
[1 2 3 4 5 6]


In [ ]:
# 16. Useful NumPy Functions

import numpy as np

# zeros()
print("Zeros:")
print(np.zeros(5))

# ones()
print("\nOnes:")
print(np.ones(5))

# arange()
print("\nArange from 1 to 10:")
print(np.arange(1, 11))

# arange() with step
print("\nArange with step 2:")
print(np.arange(0, 11, 2))


Zeros:
[0. 0. 0. 0. 0.]

Ones:
[1. 1. 1. 1. 1.]

Arange from 1 to 10:
[ 1  2  3  4  5  6  7  8  9 10]

Arange with step 2:
[ 0  2  4  6  8 10]


In [ ]:
# 17. Random Numbers

import numpy as np

# Generate 10 random integers
marks = np.random.randint(40, 100, 10)

# Print random marks
print("Random Marks:")
print(marks)


Random Marks:
[44 75 60 45 61 91 58 95 53 92]
